#!/bin/bash
# Usage: git open-pr [<branch-name>]
#
# from: https://github.com/github/hub/issues/849
# symlink from somewhere in your path (ex: /usr/local/bin)
# Navigates to the pull request for a branch using the web browser.
# Defaults to current branch.
set -e

branch="${1:-$(git symbolic-ref HEAD)}"
branch="${branch#refs/heads/}"

remote_url() {
  git remote -v | grep "^$1" | head -1 | grep -o 'github.com[/:]\S\+'
}

url="$(remote_url upstream || true)"
url="${url:-$(remote_url github || true)}"
url="${url:-$(remote_url origin || true)}"
url="${url%.git}"

open "https://${url/://}/pull/${branch//\//%2F}"