#!/bin/bash
# symlink this from /usr/local/bin (or other place on your path) and it should work
for k in `git branch|perl -pe s/^..//`;do echo -e `git show --pretty=format:"%Cgreen%ci %Cblue%cr%Creset" $k|head -n 1`\\t$k;done|sort -r | head -${1:-20}